[package]
name = "rs_in_hs"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["staticlib"]

[dependencies]
flume = { version = "0.12.0", features = ["select"] }
serde = { version = "1", features = ["derive"] }
serde_store = "0.2.2"
